services:
        app:
                build:
                        context: .
                        dockerfile: Dockerfile
                command: >
                        sh -c " python prompt_template.py && streamlit run main.py"
                ports:
                        - "8501:8501"
                env_file:
                        - .env
                stdin_open: true
                tty: true
                container_name: streamlit_summarizer_container
                        
